<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkoutSDWAN</name>
   <tag></tag>
   <elementGuidId>763ab264-25e0-4e25-971a-cc76fa5de2a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[6]/div/section/div/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div/div/ul/li[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
