<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkoutOneTimeCharge</name>
   <tag></tag>
   <elementGuidId>8142a4f7-d07e-4e5b-89af-89a8b8136a2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[6]/div/section/div/div[2]/div/div[2]/div[1]/div/div[4]/div[1]/h5/button/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
