<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkoutMPLS</name>
   <tag></tag>
   <elementGuidId>e3a23e9f-90cb-4277-902b-d6338a78ae21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[6]/div/section/div/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div/div/ul/li[2]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
