<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkoutInstall</name>
   <tag></tag>
   <elementGuidId>da6c444f-03e7-43b0-a01d-6ed6d7ffbc33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[6]/div/section/div/div[2]/div/div[2]/div[1]/div/div[4]/div[2]/div/div/ul/li[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
