<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>whatAreYouShopping</name>
   <tag></tag>
   <elementGuidId>2a8f1c21-10b4-479c-b699-ff8e446a1101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@class, 'cartheading')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@class=&quot;cartheading_h2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;cartheading_h2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cartheading</value>
   </webElementProperties>
</WebElementEntity>
